apiVersion: apps/v1
kind: Deployment
metadata:
    name: discover2
spec:
    selector:
        matchLabels:
            app: discover2
    replicas: 2
    template:
        metadata:
            labels:
                app: discover2
        spec:
            containers:
                - name: discover-api2
                  imagePullPolicy: Never
                  image: local/discover:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: discover2
spec:
    type: LoadBalancer
    selector:
        app: discover2
    ports:
        - port: 8080
