name: CI2
on:   
  - push 
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: some name for my job1
    steps:
    - name: minikube step
      id: hello
      uses: medyagh/minikube-action@master
      with:
        who-to-greet: 'Mona the Octocat'
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Get the output driver
      run: echo "The driver was ${{ steps.hello.outputs.user_driver }}"