name: CI
on:   
  - push 
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy 
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/minikube-action@master
      # now you can run kubectl to see the pods in the cluster
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: build docker image in minikube
      run: | 
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        make build-image
        echo -n "verifying images:"
        docker images
        

      